# Generated by Django 5.0 on 2023-12-22 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_alter_album_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='musician',
            new_name='musicians',
        ),
    ]
