# Generated by Django 5.0 on 2023-12-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='TaskAssignDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
