# Generated by Django 5.0 on 2023-12-21 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_alter_task_taskassigndate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='TaskAssignDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
