# Generated by Django 5.0 on 2023-12-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_alter_task_taskassigndate'),
        ('category', '0003_remove_category_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskCategories',
            field=models.ManyToManyField(to='category.category'),
        ),
    ]
