# Generated by Django 5.0 on 2023-12-22 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_rename_musician_album_musicians'),
        ('musician', '0002_alter_musician_instrument_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='musician',
            new_name='musicians',
        ),
    ]
