# Generated by Django 5.0 on 2023-12-20 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testmodel',
            fields=[
                ('roll', models.AutoField(primary_key=True, serialize=False)),
                ('big_integer_field', models.BigIntegerField(default=0)),
                ('num', models.BinaryField(default=b'\x00')),
                ('boolean_field', models.BooleanField(default=False)),
                ('char_field', models.CharField(default='', max_length=255)),
                ('date_field', models.DateField(default='2023-01-01')),
                ('date_time_field', models.DateTimeField(default='2023-01-01T00:00:00')),
                ('decimal_field', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('duration_field', models.DurationField(default=datetime.timedelta(days=1))),
                ('email_field', models.EmailField(default='', max_length=254)),
                ('file_field', models.FileField(default='', upload_to='files/')),
                ('file_path_field', models.FilePathField(default='', path='/path/to/files/')),
                ('float_field', models.FloatField(default=0.0)),
                ('generic_ip_address_field', models.GenericIPAddressField(default='0.0.0.0')),
                ('image_field', models.ImageField(default='', upload_to='images/')),
                ('integer_field', models.IntegerField(default=0)),
                ('json_field', models.JSONField(default=dict)),
                ('slug_field', models.SlugField(default='')),
                ('small_integer_field', models.SmallIntegerField(default=0)),
                ('text_field', models.TextField(default='')),
                ('time_field', models.TimeField(default='00:00:00')),
                ('url_field', models.URLField(default='')),
            ],
        ),
    ]
