# Generated by Django 5.0 on 2023-12-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='char_field',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='name',
            field=models.CharField(default='sakib', max_length=255),
        ),
    ]
