# Generated by Django 5.0 on 2023-12-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_task_category_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tasks',
        ),
    ]
